### PR TITLE
Take tax_category from Line Items and Fix validation: rounding for subcent amounts

### LINKED ISSUE #13: Tax rounding fails validation errors
If you have an invoice with an item at a tax rate of 7%, for 2.50 (2.68 including 18c tax), the current validation fails in two places:

- comparing the whole invoice (because of forced rounding down it compares 17c to 18c)
- comparing on the invoice_item level (because of no rounding at all it compares 17.5c to 18c)

PR incoming

### LINKED ISSUE #16: [Bug] Invalid e-invoice if original invoice includes both items with, and without taxes
If original invoice includes both items with, and without taxes, the e-invoice does not pass validation.

This is because we are using the invoice.tax_category on each of the possible multiple taxes an invoice can have.
This is fine as long all taxes are e.g. STANDARDRATE, but if one of those is e.g. ZEROTAXPRODUCTS and the others are STANDARDRATE, things break.

Proposed solution (It already kinda works for me locally, just no specs yet etc):

Since we are building the taxes from the invoice items anyway, we can add a new field tax_category to Tax.rb
When looping through the items to create the tax objects, we can assign the already existing item.tax_category to it.
This would also render Invoice.tax_category nearly obsolete, which is then only really used in tax_reason_text, which is only used at the per-tax level, so that also could be changed to not use invoice.tax_category

### PR DESCRIPTION
**Pull request by SubandiK**
Now taking the tax_category, which is set per tax rate, from the line_items.
This is needed because different taxes can be on one invoice, and they aren't all guaranteed to be of the same category
(see #16)

See also my comment from there:

> This would also render Invoice.tax_category nearly obsolete, which is then only really used in tax_reason_text, which is only used at the per-tax level, so that also could be changed to not use invoice.tax_category

I kept that part in place because I wanted to change as little as possible, but in theory I could also do that.

Also changing the rounding in the validation in two places:

- on the invoice, use .round(2) instead of .round(2, :down). As far as I understand, in Germany there is no forced rounding down
- on the invoice item, introduce .round(2) as well

the resulting invoice passes schematron and various online zugferd checkers.

fix #13 
fix #16

### CODE REVIEW

File: test/invoice_test.rb [hunk 1]
```diff
@@ -130,27 +130,27 @@ def make_de_invoice_with_multiple_tax_rates
       )
       line_item = LineItem.new(
         name: 'Depfu Starter Plan',
-        quantity: 1,
+        quantity: 2,
```
Comment (SubandiK) [inline test/invoice_test.rb:133]: I changed the quantity here, because I wanted a quantity of 1 for the 7% item, to show the rounding problem
